{% set name = "wagtail-json-widget" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cursive-works/wagtail-json-widget/archive/{{ version }}.tar.gz
  sha256: 2d80976cc7d9d0754b06a0779ff10ad76b89b38570f597b2231cb1ea61a9359c 

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - wagtail >=4.0

test:
  imports:
    - wagtail_json_widget
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/cursive-works/wagtail-json-widget
  summary: JSON editing for Wagtail 
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
